### PR TITLE
Fix debounce by updating popover returnFocus

### LINKED ISSUE #495: Debounce stopped working in DatePickerInput in 0.15.2
When `debounce=True`, the value is updated when the input loses focus.  

In a recent [Mantine update](https://github.com/mantinedev/mantine/commit/7dbda1e6f2c95aaf1e52251b1874c15de2e59872#diff-8e830fef686217ced24afe002b543505b26c944ca69a51d5b840e156664304f1R164), they changed the default popover prop  `returnFocus` to false,  which meant that the Input wasn't focused after the dates were selected.  This broke the debounce because it wasn't possible to update the value when the input loses focus. 

```python
import dash_mantine_components as dmc
from dash import Dash, _dash_renderer, Input, Output, html, callback
_dash_renderer._set_react_version("18.2.0")

app = Dash(external_stylesheets=dmc.styles.ALL)

from datetime import datetime, date, timedelta


component = html.Div(
    [
        dmc.DatePickerInput(
            id="date-picker-input-multiple",
            label="Pick dates",
            description="Pick one or more dates",
            minDate=date(2020, 8, 5),
            value=[datetime.now().date(), datetime.now().date() + timedelta(days=5)],
            w=400,
            type="multiple",
            placeholder="Pick dates",
            maw=300,
            clearable=True,
            debounce=True,
            popoverProps={"returnFocus": True}   # this is now required for the debounce to work.
        ),
        dmc.Space(h=10),
        dmc.Text(id="selected-date-input-multiple"),
    ]
)


@callback(
    Output("selected-date-input-multiple", "children"),
    Input("date-picker-input-multiple", "value"),
)
def update_output(dates):
    return str(dates)

app.layout = dmc.MantineProvider(
    component
)

if __name__ == "__main__":
    app.run(debug=True)




```

### PR DESCRIPTION
**Pull request by AnnMarieW**
closes #495 

When `debounce=True`, the value is updated when the input loses focus.  

In a recent [Mantine update](https://github.com/mantinedev/mantine/commit/7dbda1e6f2c95aaf1e52251b1874c15de2e59872#diff-8e830fef686217ced24afe002b543505b26c944ca69a51d5b840e156664304f1R164), they changed the default popover prop  `returnFocus` to false,  which meant that the Input wasn't focused after the dates were selected.  This broke the debounce because it wasn't possible to update the value when the input loses focus. 

```python
import dash_mantine_components as dmc
from dash import Dash, _dash_renderer, Input, Output, html, callback
_dash_renderer._set_react_version("18.2.0")

app = Dash(external_stylesheets=dmc.styles.ALL)

from datetime import datetime, date, timedelta


component = html.Div(
    [
        dmc.DatePickerInput(
            id="date-picker-input-multiple",
            label="Pick dates",
            description="Pick one or more dates",
            minDate=date(2020, 8, 5),
            value=[datetime.now().date(), datetime.now().date() + timedelta(days=5)],
            w=400,
            type="multiple",
            placeholder="Pick dates",
            maw=300,
            clearable=True,
            debounce=True,
        #    popoverProps={"returnFocus": True}   # this was required in order for the debounce to work in 0.15.2
        ),
        dmc.Space(h=10),
        dmc.Text(id="selected-date-input-multiple"),
    ]
)


@callback(
    Output("selected-date-input-multiple", "children"),
    Input("date-picker-input-multiple", "value"),
)
def update_output(dates):
    return str(dates)

app.layout = dmc.MantineProvider(
    component
)

if __name__ == "__main__":
    app.run(debug=True)




```

### CODE REVIEW

File: src/ts/components/dates/DatePickerInput.tsx [hunk 1]
```diff
@@ -101,6 +101,7 @@ const DatePickerInput = (props: Props) => {
                 minDate={stringToDate(minDate)}
                 maxDate={stringToDate(maxDate)}
                 excludeDate={isExcluded}
+                popoverProps={{returnFocus: true}}
                 {...others}
```
Comment (alexcjohnson) [inline src/ts/components/dates/DatePickerInput.tsx:105]: Would we want to merge this with any `popoverProps` you provide explicitly? ie pull `popoverProps` out of `props`, then here:
```
popoverProps={{returnFocus: true, ...popoverProps}}
```

Comment (AnnMarieW) [reply src/ts/components/dates/DatePickerInput.tsx:105]: oh nice catch - yes, that's how it should work.

Comment (AnnMarieW) [reply src/ts/components/dates/DatePickerInput.tsx:105]: That needs to be applied to #471 too

**Review by alexcjohnson — APPROVED** [review]
💃
