### PR TITLE
Fixing access to MenuTarget.boxWrapperProps

### LINKED ISSUE #285: MenuTarget boxWrapperProps property does not work with setting "width"
From the code below:

`dmc.Menu(
            [
                dmc.MenuTarget(
                    dmc.Button(
                        'Go to page',
                        fz="13px",
                        bg=button_background_color,
                        color="#FFFFFF",
                        size="sm",
                        radius="10px",
                        className="pageLinkButton",
                        w="100%",
                        disabled=page_link.is_disabled,
                    ),
                    boxWrapperProps={
                        "w": "100% !important",
                    }
                ),
                dmc.MenuDropdown(
                    ...
`

The boxWrapperProps parameter (dict) does not do any affect to the width that is set by MenuTarget, which is "fit-content".
image

### PR DESCRIPTION
**Pull request by datenzauberai**
This would fix #285.

```
from dash import Dash, _dash_renderer
import dash_mantine_components as dmc
from dash_iconify import DashIconify

_dash_renderer._set_react_version("18.2.0")

app = Dash(external_stylesheets=dmc.styles.ALL)


def menu_layout(boxWrapperProps):
    return dmc.Menu(
        [
            dmc.MenuTarget(
                dmc.Button("Click for options!", fullWidth=True), boxWrapperProps=boxWrapperProps
            ),
            dmc.MenuDropdown(
                [
                    dmc.MenuItem(
                        "External Link",
                        href="https://www.github.com/snehilvj",
                        target="_blank",
                        leftSection=DashIconify(icon="radix-icons:external-link"),
                    ),
                    dmc.MenuItem("Useless Button"),
                ]
            ),
        ]
    )

app.layout = dmc.MantineProvider(
    dmc.Container(
        dmc.Stack([
            menu_layout({}),
            menu_layout({"w": "300px"}),
            menu_layout({"w": "100%"})
        ], align="center", gap="md"),
        style={"padding": "1rem"}
    ),
    id="theme-provider",
    forceColorScheme="light"
)

if __name__ == "__main__":
    app.run(debug=True)
```

### CODE REVIEW

**Comment by AnnMarieW** [comment]
Hi @datenzauberai 
Thanks so much for the PR!

@snehilvj, I checked out this PR and ran the sample app to verify that it works and will fix the issue as reported in # 285.  It would be great to get this in the next release.

@datenzauberai would you like to include a changelog entry as well?

**Comment by datenzauberai** [comment]
> @datenzauberai would you like to include a changelog entry as well?
Sure, though I don’t really know what that exactly means 😁 could you give me a hint?

File: src/ts/components/core/menu/Menu.tsx [hunk 1]
```diff
@@ -46,7 +46,7 @@ const Menu = (props: Props) => {
             {React.Children.map(children, (child: any, index) => {
                 const childType = child.props._dashprivate_layout.type;
                 if (childType === "MenuTarget") {
-                    const { boxWrapperProps } = child.props;
+                    const { boxWrapperProps } = child.props._dashprivate_layout.props;
                     const boxProps = { w: "fit-content", ...boxWrapperProps };
```
Comment (alexcjohnson) [inline src/ts/components/core/menu/Menu.tsx:50]: Not a big deal, but this could be simplified a bit - in the process reducing similar confusion in the future - by explicitly pulling out the real child props:
```js
const {type: childType, props: childProps} = child.props._dashprivate_layout;
if (childType === "MenuTarget") {
    const { boxWrapperProps } = childProps;
    return (
        <MantineMenu.Target key={index}>
            <Box w="fit-content" {...boxWrapperProps}>{child}</Box>
```

**Review by alexcjohnson — APPROVED** [review]
💃

File: src/ts/components/core/menu/Menu.tsx (hunk 1 above)
Comment (AnnMarieW) [reply src/ts/components/core/menu/Menu.tsx:50]: Yes, that’s better - I’ll make the change before merging.
Thanks for the tip :-)

**Comment by AnnMarieW** [comment]
@datenzauberai - When I responded to Alex's review I forgot that this was your PR rather than one of mine.  Would you like to make the small recommended update?  If not, I can look after it :-)

**Comment by AnnMarieW** [comment]
Ok - done.  Thanks again for your contribution @datenzauberai  - this will be in the next release (coming soon!)
