### PR TITLE
fix closeButtonProps and clearButtonProps

### LINKED ISSUE #492: [bug] errors with  closeButtonProps in dmc.Modal (and others ...ButtonProps).  Issues with clear button and clearButtonProps
Hi,

Since 0.15.2 my Modal Is creating a React error.

It happens when i'm using closeButtonProps={"children" : dmc.Text() } (or any Components, dash.html included). 

Sample to reproduce bug :

```python
import dash_mantine_components as dmc
from dash import Dash, _dash_renderer, html
import datetime

_dash_renderer._set_react_version("18.2.0")

app = Dash(__name__)

app.layout = dmc.MantineProvider(
    dmc.Center(
        [
            dmc.Modal(
                title="New Modal",
                id="modal-simple",
                opened=True,
                children=[
                    dmc.Text("I am a modal component."),
                ],
                closeButtonProps={
                    "children" : html.H1("Hi")
                }
            ),
            # dmc.DatePickerInput(
            #     value=datetime.datetime.now().date(),
            #     label="Date clearable",
            #     w=200,
            #     clearable=True,
            #     clearButtonProps={
            #         "children" : dmc.Text("Hi")
            #     }
            # ),
        ],
        style={"height": '100vh', "width": "100vw"},
    )
)



if __name__ == "__main__":
    app.run_server(debug=True)
```

Error from Console : 

```console
hook.js:608 Error: Objects are not valid as a React child (found: object with keys {props, type, namespace}). If you meant to render a collection of children, use an array instead.
    at throwOnInvalidObjectType (react-dom@18.v2_17_1m1721817131.2.0.js:14897:11)
    at createChild (react-dom@18.v2_17_1m1721817131.2.0.js:15149:9)
    at reconcileChildrenArray (react-dom@18.v2_17_1m1721817131.2.0.js:15414:27)
    at reconcileChildFibers (react-dom@18.v2_17_1m1721817131.2.0.js:15831:18)
    at reconcileChildren (react-dom@18.v2_17_1m1721817131.2.0.js:19177:30)
    at updateHostComponent (react-dom@18.v2_17_1m1721817131.2.0.js:19934:5)
    at beginWork (react-dom@18.v2_17_1m1721817131.2.0.js:21628:16)
    at beginWork$1 (react-dom@18.v2_17_1m1721817131.2.0.js:27436:16)
    at performUnitOfWork (react-dom@18.v2_17_1m1721817131.2.0.js:26567:14)
    at workLoopSync (react-dom@18.v2_17_1m1721817131.2.0.js:26476:7) Error Component Stack:
    at ComponentErrorBoundary (ComponentErrorBoundary.react.js:6:24)
    at BaseTreeContainer (TreeContainer.js:101:24)
    at DashWrapper (TreeContainer.js:88:31)
    at div (<anonymous>)
    at dash_mantine_components.v0_15_2m1737992795.js:2:1641474
    at dash_mantine_components.v0_15_2m1737992795.js:2:1314963
    at l (dash_mantine_components.v0_15_2m1737992795.js:2:1021928)
    at CheckedComponent (TreeContainer.js:46:12)
    at ComponentErrorBoundary (ComponentErrorBoundary.react.js:6:24)
    at BaseTreeContainer (TreeContainer.js:101:24)
    at DashWrapper (TreeContainer.js:88:31)
    at c (dash_mantine_components.v0_15_2m1737992795.js:2:1664578)
    at p (dash_mantine_components.v0_15_2m1737992795.js:2:1662861)
    at l (dash_mantine_components.v0_15_2m1737992795.js:2:1190940)
    at CheckedComponent (TreeContainer.js:46:12)
    at ComponentErrorBoundary (ComponentErrorBoundary.react.js:6:24)
    at BaseTreeContainer (TreeContainer.js:101:24)
    at DashWrapper (TreeContainer.js:88:31)
    at div (<anonymous>)
    at div (<anonymous>)
    at div (<anonymous>)
    at GlobalErrorOverlay (GlobalErrorOverlay.react.js:9:24)
    at div (<anonymous>)
    at DebugMenu (DebugMenu.react.js:45:24)
    at div (<anonymous>)
    at UnconnectedGlobalErrorContainer (GlobalErrorContainer.react.js:7:24)
    at ConnectFunction (connect.js:218:75)
    at UnconnectedContainer (APIController.react.js:35:9)
    at ConnectFunction (connect.js:218:75)
    at UnconnectedAppContainer (AppContainer.react.js:13:24)
    at ConnectFunction (connect.js:218:75)
    at Provider (Provider.js:7:3)
    at AppProvider (AppProvider.react.tsx:6:24)
```

Same problem with DatePickerInput's clearButtonProps property, so i'm guessing it's impacting every ...ButtonProps

### PR DESCRIPTION
**Pull request by AnnMarieW**
closes #492 

- [x] fix modal `closeButtonProps`    
- [x] fix `clearButtonProps`

sample app on [PyCafe](https://py.cafe/snippet/dash/v1?#c=H4sIAFVFmWcEA8VWzW7jNhB-FUG9eAFJ_pGdTQwIWGz30BzaLdoFeogCgZbomDFFqiRlRwny7v2Gkh07m216KwPEHs7MN_9DP4Wlrni4DHMl6kYbF1TMboqaKScUL0qNS8WVswGzQVWXuVobXXuhYFD4gu9RUHg9w1XFDTdRsHG1jIKvrWtaFwXXyn_86ZjjUVAyKVes3ObqBK4QpVZi3Z3CXvdXuTpHTwrLHShWumLHjRVajfJwepnMkkkefiBY1jRB5jFGRaFYzYvC3x8DApdcTL6I3ShXAc5N_0EHgSafW-c87teGq-BXXTGZh1EgqiwPa6Liitc6XnkxWI3O1b3CgHw4TjjJof4b3x8BzyVO0C3yIPl3EqXUlve-_W50Y7Oncz6dPCw3QlZIVx4uT8IMe-2XMLr4mI_zCA4nD6kqhHJSjhHdQd2wSjzERNhlabS1cSlMKXlFBkottSEhIt-Gtq6jAJfBUx7uReU29P1i8vxK-DV9iC07KdjhUOa_8QeHWK8DVgdCBSzw-YRDQ6TJ9_7cntAH3m2uDp2USNbpllrGV7afDWR_J9COoyOwF_90aO6h9v0EwJ9XVUX8Go11mh0_JEfJs-4icVWUUpRb-6Lgx-mo8G_QjeE7eFgIJZxgsiAns2-m5eDD7Yqv-ywVZHWkymkU9BAflj2A4a41KlDaDQyKFTtjHRzGK8gyGC6wOoQqCpSyV6T0mVYVlhuM6qjiq_bOW_bZor8wQpP83QrDa7hosYto2OEU_vvuQsv11Ftr6RP62zV2OR43XVKyNR_fbcbMOLHGdhhbxdEtu_uxBxvUX5rejmeLyWQ2Ty8vF17kDQvxJJkuklncdGmscBUz1SX7jYTbrmtodZIiqKZzG61AN52u0BnxbpLMLpIpWNL3T7h8Cod1FS5niFpr94fe0_WAZEBFx-ENlzdHjmMr7Dww_aCEy-liEoW1UH_1ZNpTv3Bxt4EdIkUFtbWQ_DNQkf2ftXIoDTc_sECi8aqXhUjDCDcMn2-fo6PM0Yu3AMB80aOyN114rvvCPi144h7cuRnzfhreD30I5b2wDxGfOXA0sxlQpx8X_8Wm4wbXTL5n9CBHVunvOfLpR-_f3KJbdLklklCQIMj_FGzQY8tglq7WV5zNLyblfL1asflismAsnV2xSbVO5-tcraRQW26ybJpc4TFUJadREFk2Q5vjfZzhasMMokMzm5pJ8UjSaZJ6Fi2YLLtMpsnHfuSgmNDDOoxjqc3p-BB3QmY8kx6aHzKHQc4yjBPB_U9TO3iDAuMlzha9g2vJLMJOQaXYaZViRCAD2Kj4KSLFKq65YxVzYFwmmGmwnK2YuuNGtz5S-umh7oW6ZzNSnhJSzcy2bSzCI4lpssiVYma_YRIqyMKcgBS3Lma2U6XQdHtBQI3UTiJZIDw5bBRKGmUQYLmiGYKut55OSQxL2nRC3RFMmsxzhTK3jdOa7F1cJQtSs-KB-FNvB_0I-RgvJgcDD3mWwSkP1hqJwNM-Nujtudk-cixvn6eLXD2KBs6gb7y4tcht-PwPotAbeFAKAAA)

### CODE REVIEW

**Comment by AnnMarieW** [comment]
Here's a minimal example for the modal:

Image

```python

import dash_mantine_components as dmc
from dash import Dash, _dash_renderer, html, Output, Input, State, callback

from dash_iconify import DashIconify
_dash_renderer._set_react_version("18.2.0")

app = Dash(__name__)

component = html.Div(
    [
        dmc.Button("Open Modal", id="modal-demo-button"),
        dmc.Modal(
            title="New Modal",
            id="modal-simple",
            closeButtonProps={
                "children": html.Div(" close", id="my-component"),
                "icon": DashIconify(icon="radix-icons:cross-circled", color="red"),
                "style": {"width": 60},
            },
            children=[
                dmc.Text("I am in a modal component."),
            ],
        ),
    ]
)

app.layout = dmc.MantineProvider(component)

@callback(
    Output("modal-simple", "opened"),
    Input("modal-demo-button", "n_clicks"),
    State("modal-simple", "opened"),
    prevent_initial_call=True,
)
def modal_demo(nc1, opened):
    return not opened


if __name__ == "__main__":
    app.run_server(debug=True)




```



Here's an example showing that you can set an `icon` and `children` to  component.  Not that typically the children should not be used except for adding labels for screen readers.

https://github.com/mantinedev/mantine/blob/master/packages/%40mantine/core/src/components/CloseButton/CloseButton.tsx#L40

Image


```python
import dash_mantine_components as dmc
from dash_iconify import DashIconify
from dash import Dash, _dash_renderer
_dash_renderer._set_react_version("18.2.0")

app = Dash(external_stylesheets=dmc.styles.ALL)

component = dmc.DatePickerInput(
    label="Date clearable",
    value="2025-01-01",
    w=300,
    clearable=True,
    clearButtonProps={
        "children" : dmc.Text("C"),
        "icon": DashIconify(icon="radix-icons:cross-circled", color="red", width=30),
        "size": 24
    }
)

app.layout = dmc.MantineProvider(
    component
)

if __name__ == "__main__":
    app.run(debug=True)

```

File: src/ts/props/button.ts [hunk 1]
```diff
@@ -0,0 +1,33 @@
+import { MantineRadius, MantineSize } from "@mantine/core";
+import React from "react";
+
+export interface __CloseButtonProps {
+    /** Controls width and height of the button. Numbers are converted to rem. `'md'` by default. */
+    size?: MantineSize | (string & {}) | number;
```
Comment (alexcjohnson) [inline src/ts/props/button.ts:6]: `size` looks like the only difference between these two interfaces - if that's real, perhaps make them both inherit from a `__BaseButtonProps` or some such, to reduce duplication?

File: src/ts/props/button.ts [hunk 2]
```diff
@@ -0,0 +1,33 @@
...
+    size?: MantineSize | (string & {});
+    /** Key of `theme.radius` or any valid CSS value to set border-radius. Numbers are converted to rem. `theme.defaultRadius` by default. */
+    radius?: MantineRadius;
+    /** Sets `disabled` and `data-disabled` attributes on the button element */
+    disabled?: boolean;
+    /** `X` icon `width` and `height`, `80%` by default */
+    iconSize?: number | string;
+    /** Content rendered inside the button, for example `VisuallyHidden` with label for screen readers */
+    children?: React.ReactNode;
+    /** Replaces default close icon. If set, `iconSize` prop is ignored. */
```
Comment (alexcjohnson) [inline src/ts/props/button.ts:31]: Clear buttons still have a default "close" icon?

Comment (AnnMarieW) [reply src/ts/props/button.ts:31]: I'm kinda guessing on the clear button props because they aren't listed in their docs

https://mantine.dev/core/input/#inputclearbutton-component
https://mantine.dev/core/input/?t=props

Looking at their source code, it looks like they are taking the CloseButton and just updating it for the calculated size:
https://github.com/mantinedev/mantine/blob/master/packages/%40mantine/core/src/components/Input/InputClearButton/InputClearButton.tsx

**Review by alexcjohnson — APPROVED** [review]
💃
